### PR TITLE
Add flexbox

### PR DESCRIPTION
**Pull request by simsam0502**
I am a GSSOC'21 participant, and I was assigned to make the website responsive. I have used flexbox for enclosing the images.

### CODE REVIEW

**Comment by sgpritam** [comment]
Hey @simsam0502 pls attached the ss.

**Comment by simsam0502** [comment]
image
image
image
image

**Review by sgpritam — CHANGES_REQUESTED** [review]
Improve the flexbox

**Review by maverick1910 — COMMENTED** [review]
We have started updating our final documentation and requirement for your projects, we will start accepting PR's from  Monday. 
Also, we will create issues for new changes as well !

**Review by maverick1910 — COMMENTED** [review]
We are accepting PR's which match to the project functionalities, please check our documentation and contributors file for the further idea about the project.
You can start working on the newly generated issues that match the project requirements

**Pull request closed without merging**
