### PR TITLE
Changed the User Profile Page

### PR DESCRIPTION
**Pull request by avinashjha1320**
### Rebuild the responsive pages.html #137 

**now**
image

### CODE REVIEW

**Review by maverick1910 — CHANGES_REQUESTED** [review]
Add User profile picture area as well

**Comment by avinashjha1320** [comment]
@maverick1910 I have added the profile image.

image

**Review by maverick1910 — APPROVED** [review]
Accepted and merged

**Review by maverick1910 — COMMENTED** [review]
Label changed

**Pull request merged**
