### PR TITLE
update contributing.md

### PR DESCRIPTION
**Pull request by khareyash05**
With reference to issue #43 
Added the following -

1. Difference between GIT and GITHUB
2. How to clone,fork repository
3. How to create a branch and then use git push to push to repo
4. Create a PR
5. Squash commits in a single issue into one
6. Updating the forked and local repo as the updations are made in the upstream
@sgpritam  Have a look

### CODE REVIEW

**Review by sgpritam — APPROVED** [review]

**Comment by khareyash05** [comment]
@sgpritam Could you pls add a GSSOC label and an issue label to the same?

**Comment by khareyash05** [comment]
@maverick1910 Could you pls also add a level label to the same?

**Comment by khareyash05** [comment]
@maverick1910  Could you pls add a level label and a GSSOC label to the PR as well because adding a level label to the PR is only being counted
Thanx!

**Comment by khareyash05** [comment]
@maverick1910 @sgpritam @PoojaMittal2842  COuld you pls add a level label to the same?

**Pull request merged**
