### PR TITLE
Book Pass Page (Frontend) #84:@GulshanKataria

### PR DESCRIPTION
**Pull request by GulshanKataria**
fixes-#84

https://user-images.githubusercontent.com/66901234/111185310-d866a300-85d7-11eb-9d4c-001d80c8b3c5.mp4

### CODE REVIEW

**Review by maverick1910 — APPROVED** [review]
PR accepted and merged

**Comment by GulshanKataria** [comment]
@maverick1910 sir, can you please add level tag, otherwise it won't be considered for scoring. thank you

**Comment by GulshanKataria** [comment]
@maverick1910 please add a level label

**Comment by GulshanKataria** [comment]
@maverick1910 please add a level label

**Review by maverick1910 — COMMENTED** [review]
added a PR label

**Pull request merged**
