### PR TITLE
Adding small description to footer (issue #170)

### PR DESCRIPTION
**Pull request by ANSHIKA1806**
@PoojaMittal2842  @maverick1910  @sgpritam 
I have added a small description to about section in footer. Please review it and accept my pull request . If you need any changes let me know.
Thank you.

### CODE REVIEW

**Review by maverick1910 — APPROVED** [review]
Pr accepted and merged

**Review by maverick1910 — CHANGES_REQUESTED** [review]
please resolve branch conflicts

**Comment by ANSHIKA1806** [comment]
@maverick1910 There are no branch conflicts, What are you requesting to change? 
Please elaborate.

**Review by maverick1910 — APPROVED** [review]
merged

**Pull request merged**
