### PR TITLE
Home page changed

### PR DESCRIPTION
**Pull request by SAHU-01**
I've changed the homepage and have added the registeration part to registration.html 

alot of changes have been made to the css 
I'll be attaching images of what the site now looks like

image
image
image
image
image

For animations I've used java script as well

Do let me know your thoughts and if you wish to discuss contact me at :ankita.sahuof1@gmail.com

### CODE REVIEW

**Comment by SAHU-01** [comment]
I've made changes so that the page can adjust and look different on the basis of different screen sizes .
Do let me know if you have different logo,color and style preferences, i'll make changes accordingly then.

**Comment by sgpritam** [comment]
@SAHU-01 pls add short video of your changes (both old as well as new)

**Review by maverick1910 — COMMENTED** [review]
We have started updating our final documentation and requirement for your projects, we will start accepting PR's from  Monday. 
Also, we will create issues for new changes as well !

**Review by maverick1910 — COMMENTED** [review]
We are accepting PR's which match to the project functionalities, please check our documentation and contributors file for the further idea about the project.
You can start working on the newly generated issues that match the project requirements

**Pull request closed without merging**
