### PR TITLE
User Page

### PR DESCRIPTION
**Pull request by deek121477**
Added User page using HTML, CSS ,JS and Bootstrap

### CODE REVIEW

**Review by maverick1910 — CHANGES_REQUESTED** [review]
Please attach a picture or video of the work !

**Comment by deek121477** [comment]
User1
User

**Review by maverick1910 — APPROVED** [review]
PR Accepted and Merged

**Review by maverick1910 — CHANGES_REQUESTED** [review]
Please follow the document convention given in the main repo
Assets will have img,css,js folders
html files outside of the Assets

**Review by maverick1910 — APPROVED** [review]
PR merged and accepted

**Pull request merged**
