### PR TITLE
added page for Add New Place(frontend)

### PR DESCRIPTION
**Pull request by promaroy**
Solves #86 
Screenshot:
DelhiTourism

### CODE REVIEW

**Review by maverick1910 — APPROVED** [review]
PR accepted and merged

**Comment by promaroy** [comment]
@maverick1910  Since the PR has merged, can you please add GSSOC21 and a level tag to it? Otherwise it won't be considered for scoring

**Comment by maverick1910** [comment]
@promaroy I have added a label tag

**Comment by promaroy** [comment]
@maverick1910 you need to add difficulty level tag for scoring..eg: Level0 for easiest one and Level3 for toughest issue.

**Review by maverick1910 — COMMENTED** [review]
Difficulty tags added

**Pull request merged**
