### PR TITLE
Connected all pages together + created about us page

### PR DESCRIPTION
**Pull request by gaurav24072002**
I have made all the changes to the website that I listed in issue #116 , I'll be adding a video depicting all the changes I made on website and then @maverick1910  and @PoojaMittal2842 can merge this PR.

## What to Do next:
- Styling About us page
- Creating and Styling Places to visit Page
- Improving the Home page 
- Contact us page
- Making the website Responsive
- Then moving to back end development

Please assign it to me + add tag of gssoc '21 and level tag.

### CODE REVIEW

**Comment by gaurav24072002** [comment]
You can see The changes in this video:

https://user-images.githubusercontent.com/77109758/111599592-733cc880-87f6-11eb-91e5-35ca9df24f59.mp4

**Review by maverick1910 — CHANGES_REQUESTED** [review]
Please read the guidelines for contribution in contributors.md file in the repository, the functionality of the repository are very different to what you have carried out

**Comment by gaurav24072002** [comment]
Ya I saw the Contributors.md and I'll make sure all of the components you wanted will be added to it but till now also it looks fine to me- we have:
- ticket boking
- login/signup
- index as home
- new places as "places to visit"
So I'll be adding :
- search bar
- admin page 
- user profile page 
But till now you can merge under Gssoc '21 and please don't forgot to put label of gssoc '21 and level label.

**Comment by gaurav24072002** [comment]
@maverick1910  any update ?

**Comment by gaurav24072002** [comment]
Hey I have added the Search Button on Navbar :

https://user-images.githubusercontent.com/77109758/111772131-84f39e00-88d2-11eb-9c66-a525d0321ca5.mp4

I have also changed the Sign up to Log in as it was written in contribution.md

**Comment by gaurav24072002** [comment]
Now can you merge it ? And please add tag of GSSOC '21 and level tag also  Thank you.😊

**Review by maverick1910 — APPROVED** [review]
merged

**Pull request merged**
