### PR TITLE
Created Index Page [GSSoC'21]

### PR DESCRIPTION
**Pull request by avinashjha1320**
I have created the index page for Delhi Tourism issue no. #80.

Here is a video to the index page.
https://drive.google.com/file/d/1wo9OCxhxEzzgRoSYfWUVMGAgD2Zc1bwJ/view?usp=sharing

### CODE REVIEW

**Review by maverick1910 — CHANGES_REQUESTED** [review]
Merge Conflicts, please resolve conflicts !

**Comment by avinashjha1320** [comment]
@maverick1910 resolved the conflict.

**Review by maverick1910 — APPROVED** [review]
PR merged and accepted

**Review by maverick1910 — COMMENTED** [review]
label changed

**Pull request merged**
