### PR TITLE
fixed the issue #143

### PR DESCRIPTION
**Pull request by shitesh2607**
Now, links(Register and Login) are working, and Social icons of registration page are also visible.

Updated register

### CODE REVIEW

**Review by maverick1910 — COMMENTED** [review]
Please resolve the conflicts by tomorrow , the PR will be closed tomorrow

**Comment by shitesh2607** [comment]
Hi @maverick1910 can you plz guide me what changes you want? plz

**Review by maverick1910 — APPROVED** [review]
Please keep the pages according to the given structure , this will help you to resolve your branch conflicts

**Comment by shitesh2607** [comment]
Thank You @maverick1910 .
What should I do next?

**Comment by maverick1910** [comment]
> Thank You @maverick1910 .
> What should I do next?

You can create a fresh new PR , and that will work

**Comment by shitesh2607** [comment]
I'm trying to create new PR but it is showing " Everything Up-to-date".

**Review by maverick1910 — COMMENTED** [review]
Please clone the repository again and then make changes to the repo, it will help you to create a new PR

**Review by maverick1910 — COMMENTED** [review]
Closing the PR

**Pull request closed without merging**
