### PR TITLE
Created Home Page, Navbar, favicon

### PR DESCRIPTION
**Pull request by gaurav24072002**
Hey ! I have created the Home Page not fully but created the navbar till now and I want to build the whole home page for this website. Please assign this to me under GSSOC'21 and I'll be building the whole page for sure..
What I have done in home.html :
- Created navbar with tags of Home, About us, Book Pass, Contact us and Sign in tag as well with icons attached to it.
- Added Favicon to the website.
- added the logo to the navbar
- attached the book_pass.html , Registration.html , home.html to the tags . 

I will be making fully designed home page connected to all other pages as well and build an awesome Delhi-Tourism Website for sure.

d

you can merge it now 😅

### CODE REVIEW

**Comment by gaurav24072002** [comment]
And please add the tag for GSSOC'21 on it... Thank you

**Comment by gaurav24072002** [comment]
and Please assign this to me ....😅

**Review by maverick1910 — APPROVED** [review]
PR accepted and merged

**Comment by gaurav24072002** [comment]
could you please give this a tag of **GSSOC '21** and **assign it** to me so that I can now start building more in it like the whole homepage, with great animation and About Us Page as well.

- I have to ask you one thing that should I add this navbar to every page so that all pages can be connected to each other??

**Pull request merged**
