### PR TITLE
[GSSoC'21] Alignment and Padding of Images

### PR DESCRIPTION
**Pull request by avinashjha1320**
Aligned the image in the center with proper padding. Resolved issue number #73.
@sgpritam @khareyash05 @rajnagdeo @RiyaGupta08 @RuchiGitHu 

Before
Before 2

After
After 2
Before
Before 1

After
After 1

### CODE REVIEW

**Comment by avinashjha1320** [comment]
Can you also label this with GSSoC tag.

**Review by maverick1910 — COMMENTED** [review]
Nice Work, although we are coming up with a basic template to be developed for the UI. We will update it by tomorrow morning

**Comment by Srijan205** [comment]
I would like to work on this issue

**Comment by Srijan205** [comment]
i want to work on this issue as a participant of GSSoC'21

**Comment by maverick1910** [comment]
Sure, we will have our basic UI and requirements up by tomorrow afternoon and people can start contributing to it then.

**Comment by maverick1910** [comment]
The branch has conflicts, please resolve conflicts

**Pull request closed without merging**
