### PR TITLE
Completed The Home Page

### PR DESCRIPTION
**Pull request by gaurav24072002**
I have Completed The Home Page of the site(only Frontend).
Have A look: 

https://user-images.githubusercontent.com/77109758/112331351-d76ff880-8cde-11eb-84b3-260949092ccf.mp4

Now Working on About us Page and Making the site Responsive.

Please add the tag of GSSOC '21 and level tag as well. Thank you.

### CODE REVIEW

**Review by maverick1910 — APPROVED** [review]
merged and accepted

**Review by maverick1910 — CHANGES_REQUESTED** [review]
Branch conflicts present, Please resolve them

**Comment by gaurav24072002** [comment]
could you please help me to resolve the conflict or can I make a new pull request??

**Review by maverick1910 — APPROVED** [review]
You can make a new pr

**Comment by gaurav24072002** [comment]
ok sure thanks

**Review by maverick1910 — COMMENTED** [review]
Since you are creating a new PR , I am closing this PR

**Pull request closed without merging**
