### PR TITLE
Created the Home Page

### PR DESCRIPTION
**Pull request by gaurav24072002**
### I have Created the Fully Functional Home Page By Adding:
- Footer
- main page(About Delhi as well)
- Navbar
- Favicon
- Scroll up Button

** See The Video 👍 : **

https://user-images.githubusercontent.com/77109758/111393240-63ca5c00-86de-11eb-9111-713078100921.mp4

### What I need to do next : 
- Make The Home Page More Attractive
- Create About us Page
- Add navbar to all the page

### CODE REVIEW

**Comment by gaurav24072002** [comment]
Can you Please add The GSSOC' 21 tag on it and assign it to me

**Comment by gaurav24072002** [comment]
Any Update @PoojaMittal2842 or any other mentor on this issue ?

**Review by maverick1910 — APPROVED** [review]
PR Merged

**Comment by maverick1910** [comment]
> Any Update @PoojaMittal2842 or any other mentor on this issue ?

@gaurav24072002 , i have created an issue for this page, please text me over there so that I can assign you one

**Pull request merged**
