### PR TITLE
Created the Backend Folder Structure

### PR DESCRIPTION
**Pull request by K-jais**
Created the backend folder structure and added the tech stacks like Node.js, Express.js, Ejs, Html, CSS, Javascript.
I have added like this,
public->images,styles,js,etc. of both User and Admin.
views->ejs of both User and Admin.
and also added the app.js.

### CODE REVIEW

**Comment by K-jais** [comment]
It solves issue #173

**Comment by K-jais** [comment]
Sir, please review this PR before merging any other PR.

**Comment by K-jais** [comment]
Sir @maverick1910 once look into this.

**Review by maverick1910 — CHANGES_REQUESTED** [review]
Please resolve branch conflicts

**Pull request closed without merging**
